name: Workflow com falha de dependências

on:
  push:
    branches:
      - main
      - master
      - develop
      - hotfix/*
  pull_request:
    branches:
      - main
      - master
      - develop
      - hotfix/*

jobs:
  